#!/usr/bin/env python3
"""Splice references/principles.md into every agent prompt.

The seven principles must be in each agent's system prompt, not merely
reachable by it. In this repo they used to arrive through
`instructions: ["AGENTS.md"]` in opencode.json - but that is project-scoped, and
the agents' whole purpose after packaging is to run inside *someone else's*
project, where no such config exists. So the text is generated into each prompt
and this script is the only thing allowed to write it.

    python scripts/gen_agents.py            # rewrite the agent files
    python scripts/gen_agents.py --check    # exit 1 if any file is out of date

`--check` is what tests/test_agent_config.py runs. Standard library only: this
must work before `uv sync` has ever run.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PRINCIPLES = ROOT / "references" / "principles.md"
AGENT_DIR = ROOT / ".opencode" / "agent"

BEGIN = "<!-- BEGIN PRINCIPLES: generated by gen_agents.py - do not edit -->"
END = "<!-- END PRINCIPLES -->"

BLOCK_RE = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END),
    re.DOTALL,
)


def principles_body() -> str:
    """The principles text, minus its maintainer-facing HTML comment header."""
    text = PRINCIPLES.read_text()
    # Drop every leading HTML comment: those are notes to whoever edits the
    # source file and have no business in five system prompts.
    while text.lstrip().startswith("<!--"):
        text = text.lstrip()
        end = text.index("-->") + 3
        text = text[end:]
    return text.strip()


def rendered_block() -> str:
    return f"{BEGIN}\n\n{principles_body()}\n\n{END}"


def apply(path: Path, block: str) -> str:
    original = path.read_text()
    if not BLOCK_RE.search(original):
        raise SystemExit(
            f"{path.relative_to(ROOT)} has no principles markers.\n"
            f"Add these two lines where the principles belong:\n  {BEGIN}\n  {END}"
        )
    return BLOCK_RE.sub(lambda _: block, original, count=1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if any agent file is out of date",
    )
    args = parser.parse_args()

    block = rendered_block()
    stale: list[str] = []
    for path in sorted(AGENT_DIR.glob("*.md")):
        updated = apply(path, block)
        if updated == path.read_text():
            continue
        stale.append(str(path.relative_to(ROOT)))
        if not args.check:
            path.write_text(updated)

    if args.check:
        if stale:
            print(
                "The principles block is out of date in:\n  "
                + "\n  ".join(stale)
                + "\n\nRegenerate with: python scripts/gen_agents.py",
                file=sys.stderr,
            )
            return 1
        print(f"principles in sync across {len(list(AGENT_DIR.glob('*.md')))} agent(s)")
        return 0

    if stale:
        print("updated:\n  " + "\n  ".join(stale))
    else:
        print("already up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
